dist: trusty

language: php

services:
  - rabbitmq

cache:
    directories:
        - $HOME/.composer/cache/files

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly
  - hhvm-3.18

before_install:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/behat
